PSPageControlProtocol and example applying the new protocol
sochalewski/PSPageControl pull request #3
Opened 2017-10-15 15:30 UTC by afrodev

- CurrentViewIndex now is public and has didSet
- PSPageControlProtocol added to get when CurrentViewIndex changed
- Example applying the new PSPageControlProtocol

2017-10-18 09:32 UTC, sochalewski requested changes
Thank you for your PR! I added these two comments, so after these changes I'll easily merge it.

2017-10-18 09:32 UTC, sochalewski commented on PSPageControl.swift
> +    open var delegate: PSPageControlProtocol?
I believe it should be a `weak` variable.

2017-10-18 09:32 UTC, sochalewski commented on PSPageControl.swift
> +public protocol PSPageControlProtocol {
`PSPageControlDelegate` fits better naming convention.

2017-10-19 13:59 UTC, afrodev commented
Ok, thanks for answer I will send a new pull request for you!

2017-10-19 13:59 UTC, closed without merging